version: '3.4'

services:
  newsportal:
    image: newsportal
    build:
      context: .
      dockerfile: NewsPortal/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - news-data:/app
volumes:
  news-data:
